[general]
host = "0.0.0.0"
port = 6432
admin_username = "admin"
admin_password = "admin_password"
log_level = "info"
noreply_logging = false

[pools.traveler_api_db]
pool_mode = "session"
default_role = "primary"

[pools.traveler_api_db.users.postgres]
username = "postgres"
password = "09125689"
pool_size = 10

[pools.traveler_api_db_read]
pool_mode = "session"
default_role = "replica"

[pools.traveler_api_db_read.users.postgres]
username = "postgres"
password = "09125689"
pool_size = 10

[pools.traveler_api_db.shards.0]
database = "traveler_api_db"
servers = [
    ["traveler-db", 5432, "primary"],
]

[pools.traveler_api_db_read.shards.0]
database = "traveler_api_db"
servers = [
    ["traveler-db-replica-1", 5432, "replica"],
    ["traveler-db-replica-2", 5432, "replica"]
]